test1

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -30,6 +30,14 @@ jobs:
         cache: maven
     - name: Build with Maven
       run: mvn clean install -DskipTests
+    - name: Check for build errors
+      run: |
+         if [ $? -eq 0 ]; then
+           echo "Build successful"
+         else
+           echo "Build failed"
+           exit 1
+         fi
 #      run: mvn -B package --file pom.xml
 
     # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
